### ISSUE TITLE
Sample code not working 

### ISSUE THREAD

**Issue by harshakhmk** [pekc83/bge#1]
Hi, I am using bge crate https://crates.io/crates/bge
Which is requiring ort version 2.0.0-rc.0, when I was running my sample it is giving error
```
No method named with model from file formed for struck session builder in the current scope
let model= ort:: Session::builder()?.with_model_from_file(model_file_path)

No method name extract answer found for struct value in the current scope
let output= outputs ["last_hidden_state"]
                   . extract_tensor::<f32>()

**Comment by pekc83** [comment]
Probably you use `ort` crate version `2.0.0-rc.1` in your Cargo.toml
Currently this crate works with `2.0.0-rc.0`, but I'll update it soon to use `rc.1`

**Comment by harshakhmk** [comment]
I just checked, did not work with neither of the versions

**Comment by pekc83** [comment]
Now you can use `bge = "0.2.0"`. It works with `ort = "2.0.0-rc.1"`

**Comment by harshakhmk** [comment]
Thanks it worked
